### ISSUE TITLE
Just admin-pw works

### ISSUE THREAD

**Issue by unrealmarmota** [TrimVis/butlarr#28]
I setup butlarr as described with the config assistant, but neither the user nor the mods password seems to authenticate a user.
No problems with the admin-pw though.
Any advice?

**Comment by Klubas** [comment]
I experienced the same issue, but thought I was doing something wrong and didn't dig further because I'm the only user.

**Comment by Klubas** [comment]
@TrimVis any ideia what the cause may be? I can take a look but I'm not really familiar with the authentication part of the project.

**Comment by TrimVis** [comment]
I'm looking into it right now, thanks for the report :)

**Comment by TrimVis** [comment]
I just checked the code and I don't see anything that looks immediately wrong.
What response are you getting when trying to authenticate?
Is it just wrong password, or no response at all?

**Comment by TrimVis** [comment]
I just now created the following config using the autosetup and have no issues with authorization...

```yaml
apis:
  series:
    api_host: "http://localhost:8989/"
    api_key: "abcdefghijkl"
auth_passwords:
  admin: adminpw
  mod: modpw
  user: userpw
services:
- api: series
  commands:
  - series
  type: Sonarr
telegram:
  token: "123456789:abcdefghijklm"
```
It's a requirement for the passwords to be different between the roles. In case they are the same, the highest level access will be assigned (e.g. if all passwords are the same, admin will always be assigned).

@Klubas @unrealmarmota Can you maybe provide some logs and the response you receive?
